import type { ReportLanguage } from '../types/analysis';

export const normalizeReportLanguage = (value?: string | null): ReportLanguage =>
  value === 'en' ? 'en' : value === 'ko' ? 'ko' : 'zh';

const REPORT_TEXT = {
  zh: {
    keyInsights: '核心洞察',
    noAnalysisSummary: '暂无分析结论',
    actionAdvice: '操作建议',
    noAdvice: '暂无建议',
    trendPrediction: '趋势预测',
    noPrediction: '暂无预测',
    marketSentiment: '市场情绪',
    strategyPoints: '策略点位',
    sniperLevels: '狙击点位',
    idealBuy: '理想买入',
    secondaryBuy: '二次买入',
    stopLoss: '止损价位',
    takeProfit: '止盈目标',
    noValue: '—',
    newsFeed: '资讯动态',
    relatedNews: '相关资讯',
    refresh: '刷新',
    retry: '重试',
    dismiss: '关闭',
    details: '查看详情',
    loadingNews: '加载资讯中...',
    noNews: '暂无相关资讯',
    noNewsDescription: '可稍后刷新以获取最新资讯。',
    openLink: '跳转',
    transparency: '透明度',
    traceability: '数据追溯',
    rawResult: '原始分析结果',
    analysisSnapshot: '分析快照',
    copy: '复制',
    copied: '已复制',
    recordId: '记录 ID',
    fullReport: '完整分析报告',
    loadingReport: '加载报告中...',
    loadReportFailed: '加载报告失败',
    copyMarkdownSource: '复制 Markdown 源码',
    copyPlainText: '复制纯文本',
    analysisModel: '分析模型',
    fearGreedIndex: '恐惧贪婪指数',
    boardLinkage: '板块联动',
    relatedBoards: '关联板块',
    leadingBoard: '领涨',
    laggingBoard: '领跌',
    neutralBoard: '中性',
    reanalyze: '重新分析',
    strategySynthesisEyebrow: '多策略综合',
    strategySynthesisTitle: '观点共识与分歧',
    authoritativeResult: '权威结论',
    finalSignal: '最终信号',
    weightedScore: '加权得分',
    confidence: '综合置信度',
    consensusLevel: '共识度',
    conflicts: '冲突',
    validOpinions: '有效观点',
    invalidOpinions: '无效观点',
    signalDistribution: '信号分布',
    bullish: '看多',
    neutral: '中性',
    bearish: '看空',
    appliedWeight: '实际权重',
    weightShare: '权重占比',
    supportingOpinions: '支持观点',
    opposingOpinions: '反方观点',
    primaryDissent: '主要异议',
    conflictDetails: '冲突详情',
    deliberation: '协同推理',
    deliberationMode: '协调模式',
    resolutionStatus: '解决状态',
    resolvedConflicts: '已解决冲突',
    unresolvedConflicts: '未解决冲突',
    minorityView: '少数派观点',
    minorityPreserved: '已保留',
    minorityNotPreserved: '未保留',
    confidenceAdjustment: '置信度调整',
    resolutionStatusLabels: {
      unresolved: '未解决', partially_resolved: '部分解决',
    },
    conflictDescriptions: {
      directional_opposition: '策略方向出现对立：部分策略看多，部分策略看空，综合结论需要降低确定性。',
      wide_score_dispersion: '策略信号分数分布较宽，说明多策略对行情结构存在明显分歧。',
      high_confidence_dissent: '存在高置信少数派策略与综合信号明显不一致，应保留反方观点。',
      adjustment_contradiction: '策略加减分方向相互矛盾，说明不同策略对同一标的的边际评分分歧较大。',
    },
    unknownConflict: '存在未分类的策略分歧，请结合参与策略和严重程度审慎判断。',
    revisionPreview: '修订投影',
    previewNonAuthoritative: '预览（非权威，不改变最终信号）',
    showMore: '展开理由',
    showLess: '收起理由',
    noOpinions: '暂无',
    rounds: '轮次',
    responses: '回应',
    signalLabels: {
      strong_buy: '强烈买入', buy: '买入', hold: '观望', sell: '卖出', strong_sell: '强烈卖出',
    },
    consensusLabels: { high: '高', medium: '中', low: '低', insufficient: '证据不足' },
    severityLabels: { none: '无', low: '低', medium: '中', high: '高' },
  },
  en: {
    keyInsights: 'KEY INSIGHTS',
    noAnalysisSummary: 'No analysis summary yet',
    actionAdvice: 'Action Advice',
    noAdvice: 'No advice yet',
    trendPrediction: 'Trend Outlook',
    noPrediction: 'No forecast yet',
    marketSentiment: 'Market Sentiment',
    strategyPoints: 'STRATEGY POINTS',
    sniperLevels: 'Action Levels',
    idealBuy: 'Ideal Entry',
    secondaryBuy: 'Secondary Entry',
    stopLoss: 'Stop Loss',
    takeProfit: 'Take Profit',
    noValue: '—',
    newsFeed: 'NEWS FEED',
    relatedNews: 'Related News',
    refresh: 'Refresh',
    retry: 'Retry',
    dismiss: 'Close',
    details: 'View details',
    loadingNews: 'Loading news...',
    noNews: 'No related news',
    noNewsDescription: 'Refresh later to check for the latest updates.',
    openLink: 'Open',
    transparency: 'TRANSPARENCY',
    traceability: 'Data Traceability',
    rawResult: 'Raw Analysis Result',
    analysisSnapshot: 'Analysis Snapshot',
    copy: 'Copy',
    copied: 'Copied!',
    recordId: 'Record ID',
    fullReport: 'Full Analysis Report',
    loadingReport: 'Loading report...',
    loadReportFailed: 'Failed to load report',
    copyMarkdownSource: 'Copy Markdown Source',
    copyPlainText: 'Copy Plain Text',
    analysisModel: 'Model',
    fearGreedIndex: 'Fear & Greed Index',
    boardLinkage: 'BOARD LINKAGE',
    relatedBoards: 'Related Boards',
    leadingBoard: 'Leading',
    laggingBoard: 'Lagging',
    neutralBoard: 'Neutral',
    reanalyze: 'Reanalyze',
    strategySynthesisEyebrow: 'MULTI-STRATEGY',
    strategySynthesisTitle: 'Consensus and Dissent',
    authoritativeResult: 'Authoritative result',
    finalSignal: 'Final Signal',
    weightedScore: 'Weighted Score',
    confidence: 'Confidence',
    consensusLevel: 'Consensus',
    conflicts: 'Conflicts',
    validOpinions: 'Valid Opinions',
    invalidOpinions: 'Invalid Opinions',
    signalDistribution: 'Signal Distribution',
    bullish: 'Bullish',
    neutral: 'Neutral',
    bearish: 'Bearish',
    appliedWeight: 'Applied weight',
    weightShare: 'Weight share',
    supportingOpinions: 'Supporting Opinions',
    opposingOpinions: 'Opposing Opinions',
    primaryDissent: 'Primary Dissent',
    conflictDetails: 'Conflict Details',
    deliberation: 'Deliberation',
    deliberationMode: 'Coordination mode',
    resolutionStatus: 'Resolution status',
    resolvedConflicts: 'Resolved conflicts',
    unresolvedConflicts: 'Unresolved conflicts',
    minorityView: 'Minority view',
    minorityPreserved: 'Preserved',
    minorityNotPreserved: 'Not preserved',
    confidenceAdjustment: 'Confidence adjustment',
    resolutionStatusLabels: {
      unresolved: 'Unresolved', partially_resolved: 'Partially resolved',
    },
    conflictDescriptions: {
      directional_opposition: 'Strategy directions diverge: some strategies are bullish while others are bearish, so conviction should be reduced.',
      wide_score_dispersion: 'Strategy signal scores are widely dispersed, indicating meaningful disagreement on market structure.',
      high_confidence_dissent: 'A high-confidence minority strategy materially disagrees with the final signal and should be kept as a dissenting view.',
      adjustment_contradiction: 'Strategy score adjustments contradict each other, showing large disagreement in marginal scoring.',
    },
    unknownConflict: 'An unclassified strategy disagreement remains; review its participants and severity carefully.',
    revisionPreview: 'Revision Projection',
    previewNonAuthoritative: 'Preview (non-authoritative; final signal unchanged)',
    showMore: 'Show reasoning',
    showLess: 'Hide reasoning',
    noOpinions: 'None',
    rounds: 'Rounds',
    responses: 'Responses',
    signalLabels: {
      strong_buy: 'Strong Buy', buy: 'Buy', hold: 'Hold', sell: 'Sell', strong_sell: 'Strong Sell',
    },
    consensusLabels: { high: 'High', medium: 'Medium', low: 'Low', insufficient: 'Insufficient' },
    severityLabels: { none: 'None', low: 'Low', medium: 'Medium', high: 'High' },
  },
  ko: {
    keyInsights: '핵심 인사이트',
    noAnalysisSummary: '분석 결론 없음',
    actionAdvice: '대응 전략',
    noAdvice: '제안 없음',
    trendPrediction: '추세 전망',
    noPrediction: '예측 없음',
    marketSentiment: '시장 심리',
    strategyPoints: '전략 가격대',
    sniperLevels: '대응 가격대',
    idealBuy: '이상적 매수가',
    secondaryBuy: '추가 매수가',
    stopLoss: '손절가',
    takeProfit: '목표가',
    noValue: '—',
    newsFeed: '뉴스 피드',
    relatedNews: '관련 뉴스',
    refresh: '새로고침',
    retry: '다시 시도',
    dismiss: '닫기',
    details: '상세 보기',
    loadingNews: '뉴스 불러오는 중...',
    noNews: '관련 뉴스 없음',
    noNewsDescription: '잠시 후 새로고침하여 최신 소식을 확인하세요.',
    openLink: '열기',
    transparency: '투명성',
    traceability: '데이터 추적',
    rawResult: '원본 분석 결과',
    analysisSnapshot: '분석 스냅샷',
    copy: '복사',
    copied: '복사됨!',
    recordId: '레코드 ID',
    fullReport: '전체 분석 리포트',
    loadingReport: '리포트 불러오는 중...',
    loadReportFailed: '리포트 불러오기 실패',
    copyMarkdownSource: 'Markdown 소스 복사',
    copyPlainText: '일반 텍스트 복사',
    analysisModel: '분석 모델',
    fearGreedIndex: '공포·탐욕 지수',
    boardLinkage: '섹터 연동',
    relatedBoards: '관련 섹터',
    leadingBoard: '강세',
    laggingBoard: '약세',
    neutralBoard: '중립',
    reanalyze: '재분석',
    strategySynthesisEyebrow: '다중 전략 종합',
    strategySynthesisTitle: '합의와 이견',
    authoritativeResult: '권위 있는 결론',
    finalSignal: '최종 신호',
    weightedScore: '가중 점수',
    confidence: '종합 확신도',
    consensusLevel: '합의 수준',
    conflicts: '충돌',
    validOpinions: '유효 의견',
    invalidOpinions: '무효 의견',
    signalDistribution: '신호 분포',
    bullish: '상승',
    neutral: '중립',
    bearish: '하락',
    appliedWeight: '적용 가중치',
    weightShare: '가중치 비율',
    supportingOpinions: '지지 의견',
    opposingOpinions: '반대 의견',
    primaryDissent: '주요 이견',
    conflictDetails: '충돌 상세',
    deliberation: '협업 추론',
    deliberationMode: '조정 모드',
    resolutionStatus: '해결 상태',
    resolvedConflicts: '해결된 충돌',
    unresolvedConflicts: '미해결 충돌',
    minorityView: '소수 의견',
    minorityPreserved: '보존됨',
    minorityNotPreserved: '보존되지 않음',
    confidenceAdjustment: '확신도 조정',
    resolutionStatusLabels: {
      unresolved: '미해결', partially_resolved: '부분 해결',
    },
    conflictDescriptions: {
      directional_opposition: '전략 방향이 엇갈립니다. 일부 전략은 상승을, 일부 전략은 하락을 보며 확신도를 낮춰야 합니다.',
      wide_score_dispersion: '전략 신호 점수 분포가 넓어 시장 구조에 대한 전략 간 이견이 큽니다.',
      high_confidence_dissent: '높은 확신도의 소수 전략이 종합 신호와 크게 달라 반대 관점으로 보존해야 합니다.',
      adjustment_contradiction: '전략별 점수 조정 방향이 서로 충돌해 동일 종목의 한계 평가 차이가 큽니다.',
    },
    unknownConflict: '분류되지 않은 전략 이견이 있습니다. 참여 전략과 심각도를 함께 확인하세요.',
    revisionPreview: '수정 투영',
    previewNonAuthoritative: '미리보기(비권위, 최종 신호 변경 없음)',
    showMore: '근거 펼치기',
    showLess: '근거 접기',
    noOpinions: '없음',
    rounds: '라운드',
    responses: '응답',
    signalLabels: {
      strong_buy: '적극 매수', buy: '매수', hold: '보유', sell: '매도', strong_sell: '적극 매도',
    },
    consensusLabels: { high: '높음', medium: '중간', low: '낮음', insufficient: '근거 부족' },
    severityLabels: { none: '없음', low: '낮음', medium: '중간', high: '높음' },
  },
} as const;

export const getReportText = (language?: string | null) => REPORT_TEXT[normalizeReportLanguage(language)];
